# Generated by Django 3.0.6 on 2020-07-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosies_customs', '0005_auto_20200713_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='N', max_length=255),
            preserve_default=False,
        ),
    ]
