# Generated by Django 3.0.6 on 2020-07-16 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rosies_customs', '0006_auto_20200714_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
