# Generated by Django 3.0.6 on 2020-07-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosies_customs', '0009_auto_20200716_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='True'),
            preserve_default=False,
        ),
    ]
