# Generated by Django 3.0.6 on 2020-07-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rosies_customs', '0007_auto_20200716_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('timestamp', models.DateTimeField(verbose_name='%YYYY/%mm/dd')),
                ('update', models.DateTimeField(verbose_name='%YYYY/%mm/dd')),
                ('active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, to='rosies_customs.Product')),
            ],
        ),
    ]
