# Generated by Django 3.0.6 on 2020-07-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosies_customs', '0002_auto_20200707_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='I', upload_to='', verbose_name='wicked_liffe\rosies_customs\templates\\static'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
